name: lint and test

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download and setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - name: Install dependencies
        run: npm ci
      
      - name: Run Linter
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download and setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run unitTests

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download and setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - name: Install dependencies
        run: npm ci
      
      - name: Run integration tests
        run: npm run integrationTests
